--------------------------------------------------------
--  파일이 생성됨 - 토요일-7월-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "TEST_USER"."ADDRESS" 
   (	"LAT" FLOAT(53), 
	"LON" FLOAT(53), 
	"ADDR_ID" NUMBER(19,0), 
	"CRE_DTTM" TIMESTAMP (6), 
	"UPD_DTTM" TIMESTAMP (6), 
	"CITY" VARCHAR2(255 CHAR), 
	"CRE_USER_ID" VARCHAR2(255 CHAR), 
	"DETAIL" VARCHAR2(255 CHAR), 
	"DISTRICT" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"PHONE" VARCHAR2(255 CHAR), 
	"RECIPIENT_NAME" VARCHAR2(255 CHAR), 
	"UPD_USER_ID" VARCHAR2(255 CHAR), 
	"USER_ID" VARCHAR2(255 CHAR), 
	"ZIP_CODE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BAROGO_USER
--------------------------------------------------------

  CREATE TABLE "TEST_USER"."BAROGO_USER" 
   (	"FAIL_CNT" NUMBER(*,0) DEFAULT 0, 
	"PW_EXP_DATE" DATE, 
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y', 
	"VALID_YN" CHAR(1 BYTE) DEFAULT 'Y', 
	"CRE_DTTM" TIMESTAMP (6), 
	"FINISH_USE_DTTM" TIMESTAMP (6), 
	"REFRESH_EXP" TIMESTAMP (6) WITH TIME ZONE, 
	"START_USE_DTTM" TIMESTAMP (6), 
	"UPD_DTTM" TIMESTAMP (6), 
	"REFRESH_TOKEN" VARCHAR2(512 CHAR), 
	"CRE_USER_ID" VARCHAR2(255 CHAR), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"PHONE" VARCHAR2(255 CHAR), 
	"PW" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(255 CHAR), 
	"UPD_USER_ID" VARCHAR2(255 CHAR), 
	"USER_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CODE
--------------------------------------------------------

  CREATE TABLE "TEST_USER"."CODE" 
   (	"USE_YN" NUMBER(1,0), 
	"CRE_DTTM" TIMESTAMP (6), 
	"UPD_DTTM" TIMESTAMP (6), 
	"CODE" VARCHAR2(255 CHAR), 
	"CRE_USER_ID" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"UPD_USER_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CODE_DTL
--------------------------------------------------------

  CREATE TABLE "TEST_USER"."CODE_DTL" 
   (	"CRE_DTTM" TIMESTAMP (6), 
	"UPD_DTTM" TIMESTAMP (6), 
	"CODE_CODE" VARCHAR2(255 CHAR), 
	"CRE_USER_ID" VARCHAR2(255 CHAR), 
	"DETAIL_CODE" VARCHAR2(255 CHAR), 
	"DETAIL_NAME" VARCHAR2(255 CHAR), 
	"LANG_TP" VARCHAR2(255 CHAR), 
	"UPD_USER_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DRVR
--------------------------------------------------------

  CREATE TABLE "TEST_USER"."DRVR" 
   (	"DRVR_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DSPCH
--------------------------------------------------------

  CREATE TABLE "TEST_USER"."DSPCH" 
   (	"DRVR_ID" NUMBER(19,0), 
	"DSPCH_NO" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDER_DETAIL
--------------------------------------------------------

  CREATE TABLE "TEST_USER"."ORDER_DETAIL" 
   (	"QUANTITY" NUMBER(10,0), 
	"CRE_DTTM" TIMESTAMP (6), 
	"ORDER_DTL_ID" NUMBER(19,0), 
	"ORDER_ID" NUMBER(19,0), 
	"PRICE" NUMBER(19,0), 
	"UPD_DTTM" TIMESTAMP (6), 
	"VOLUMN" NUMBER(19,0), 
	"WEIGHT" NUMBER(19,0), 
	"CRE_USER_ID" VARCHAR2(255 CHAR), 
	"UNIT" VARCHAR2(255 CHAR), 
	"UPD_USER_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "TEST_USER"."ORDERS" 
   (	"DEL_YN" CHAR(1 BYTE) DEFAULT 'N', 
	"CRE_DTTM" TIMESTAMP (6), 
	"DELIVERY_DATE" TIMESTAMP (6), 
	"DELIVERY_FEE" NUMBER(19,0), 
	"DSPCH_NO" NUMBER(19,0), 
	"FRM_ADDR_ID" NUMBER(19,0), 
	"ORDER_ID" NUMBER(19,0), 
	"PAYMENT_ID" NUMBER(19,0), 
	"TO_ADDR_ID" NUMBER(19,0), 
	"TTL_PRICE" NUMBER(19,0), 
	"TTL_VOLUME" NUMBER(19,0), 
	"TTL_WEIGHT" NUMBER(19,0), 
	"UPD_DTTM" TIMESTAMP (6), 
	"CRE_USER_ID" VARCHAR2(255 CHAR), 
	"MEMO" VARCHAR2(255 CHAR), 
	"ORDER_NO" VARCHAR2(255 CHAR), 
	"STATUS" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(255 CHAR), 
	"UPD_USER_ID" VARCHAR2(255 CHAR), 
	"USER_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "TEST_USER"."PAYMENT" 
   (	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y', 
	"CRE_DTTM" TIMESTAMP (6), 
	"PAYMENT_ID" NUMBER(19,0), 
	"UPD_DTTM" TIMESTAMP (6), 
	"CODE" VARCHAR2(255 CHAR), 
	"CRE_USER_ID" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"UPD_USER_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009029
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST_USER"."SYS_C009029" ON "TEST_USER"."ADDRESS" ("ADDR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009042
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST_USER"."SYS_C009042" ON "TEST_USER"."BAROGO_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009048
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST_USER"."SYS_C009048" ON "TEST_USER"."CODE" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009055
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST_USER"."SYS_C009055" ON "TEST_USER"."CODE_DTL" ("CODE_CODE", "DETAIL_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009057
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST_USER"."SYS_C009057" ON "TEST_USER"."DRVR" ("DRVR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009060
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST_USER"."SYS_C009060" ON "TEST_USER"."DSPCH" ("DSPCH_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009061
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST_USER"."SYS_C009061" ON "TEST_USER"."DSPCH" ("DRVR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009071
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST_USER"."SYS_C009071" ON "TEST_USER"."ORDER_DETAIL" ("ORDER_DTL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_ORDER_01
--------------------------------------------------------

  CREATE INDEX "TEST_USER"."IDX_ORDER_01" ON "TEST_USER"."ORDERS" ("USER_ID", "DELIVERY_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009087
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST_USER"."SYS_C009087" ON "TEST_USER"."ORDERS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009088
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST_USER"."SYS_C009088" ON "TEST_USER"."ORDERS" ("FRM_ADDR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009089
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST_USER"."SYS_C009089" ON "TEST_USER"."ORDERS" ("PAYMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009090
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST_USER"."SYS_C009090" ON "TEST_USER"."ORDERS" ("TO_ADDR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009097
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST_USER"."SYS_C009097" ON "TEST_USER"."PAYMENT" ("PAYMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "TEST_USER"."ADDRESS" MODIFY ("LAT" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ADDRESS" MODIFY ("LON" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ADDRESS" MODIFY ("ADDR_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ADDRESS" MODIFY ("CRE_DTTM" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ADDRESS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ADDRESS" MODIFY ("CRE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ADDRESS" MODIFY ("DETAIL" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ADDRESS" MODIFY ("DISTRICT" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ADDRESS" MODIFY ("ZIP_CODE" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ADDRESS" ADD PRIMARY KEY ("ADDR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BAROGO_USER
--------------------------------------------------------

  ALTER TABLE "TEST_USER"."BAROGO_USER" MODIFY ("FAIL_CNT" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."BAROGO_USER" MODIFY ("PW_EXP_DATE" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."BAROGO_USER" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."BAROGO_USER" MODIFY ("VALID_YN" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."BAROGO_USER" MODIFY ("CRE_DTTM" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."BAROGO_USER" MODIFY ("START_USE_DTTM" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."BAROGO_USER" MODIFY ("CRE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."BAROGO_USER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."BAROGO_USER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."BAROGO_USER" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."BAROGO_USER" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."BAROGO_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."BAROGO_USER" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CODE
--------------------------------------------------------

  ALTER TABLE "TEST_USER"."CODE" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."CODE" MODIFY ("CRE_DTTM" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."CODE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."CODE" MODIFY ("CRE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."CODE" ADD CHECK (use_yn in (0,1)) ENABLE;
  ALTER TABLE "TEST_USER"."CODE" ADD PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CODE_DTL
--------------------------------------------------------

  ALTER TABLE "TEST_USER"."CODE_DTL" MODIFY ("CRE_DTTM" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."CODE_DTL" MODIFY ("CODE_CODE" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."CODE_DTL" MODIFY ("CRE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."CODE_DTL" MODIFY ("DETAIL_CODE" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."CODE_DTL" MODIFY ("DETAIL_NAME" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."CODE_DTL" MODIFY ("LANG_TP" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."CODE_DTL" ADD PRIMARY KEY ("CODE_CODE", "DETAIL_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DRVR
--------------------------------------------------------

  ALTER TABLE "TEST_USER"."DRVR" MODIFY ("DRVR_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."DRVR" ADD PRIMARY KEY ("DRVR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DSPCH
--------------------------------------------------------

  ALTER TABLE "TEST_USER"."DSPCH" MODIFY ("DRVR_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."DSPCH" MODIFY ("DSPCH_NO" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."DSPCH" ADD PRIMARY KEY ("DSPCH_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TEST_USER"."DSPCH" ADD UNIQUE ("DRVR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDER_DETAIL
--------------------------------------------------------

  ALTER TABLE "TEST_USER"."ORDER_DETAIL" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDER_DETAIL" MODIFY ("CRE_DTTM" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDER_DETAIL" MODIFY ("ORDER_DTL_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDER_DETAIL" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDER_DETAIL" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDER_DETAIL" MODIFY ("VOLUMN" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDER_DETAIL" MODIFY ("WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDER_DETAIL" MODIFY ("CRE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDER_DETAIL" MODIFY ("UNIT" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDER_DETAIL" ADD PRIMARY KEY ("ORDER_DTL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "TEST_USER"."ORDERS" MODIFY ("DEL_YN" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDERS" MODIFY ("CRE_DTTM" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDERS" MODIFY ("DELIVERY_DATE" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDERS" MODIFY ("DELIVERY_FEE" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDERS" MODIFY ("FRM_ADDR_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDERS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDERS" MODIFY ("TO_ADDR_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDERS" MODIFY ("TTL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDERS" MODIFY ("TTL_VOLUME" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDERS" MODIFY ("TTL_WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDERS" MODIFY ("CRE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDERS" MODIFY ("ORDER_NO" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDERS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDERS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."ORDERS" ADD PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TEST_USER"."ORDERS" ADD UNIQUE ("FRM_ADDR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TEST_USER"."ORDERS" ADD UNIQUE ("PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TEST_USER"."ORDERS" ADD UNIQUE ("TO_ADDR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "TEST_USER"."PAYMENT" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."PAYMENT" MODIFY ("CRE_DTTM" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."PAYMENT" MODIFY ("PAYMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."PAYMENT" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."PAYMENT" MODIFY ("CRE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."PAYMENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."PAYMENT" ADD PRIMARY KEY ("PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "TEST_USER"."ADDRESS" ADD CONSTRAINT "FK2A8N57AJF6CIX2G6FUTNQP6EW" FOREIGN KEY ("USER_ID")
	  REFERENCES "TEST_USER"."BAROGO_USER" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CODE_DTL
--------------------------------------------------------

  ALTER TABLE "TEST_USER"."CODE_DTL" ADD CONSTRAINT "FKLY49LJDYBDC210E35TYIE0XWV" FOREIGN KEY ("CODE_CODE")
	  REFERENCES "TEST_USER"."CODE" ("CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DSPCH
--------------------------------------------------------

  ALTER TABLE "TEST_USER"."DSPCH" ADD CONSTRAINT "FKPASP7C1U7JVTYU0QCGSBSSD4K" FOREIGN KEY ("DRVR_ID")
	  REFERENCES "TEST_USER"."DRVR" ("DRVR_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_DETAIL
--------------------------------------------------------

  ALTER TABLE "TEST_USER"."ORDER_DETAIL" ADD CONSTRAINT "FKRWS2Q0SI6OYD6IL8GQE2AENNC" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "TEST_USER"."ORDERS" ("ORDER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "TEST_USER"."ORDERS" ADD CONSTRAINT "FK7AV02MMY4K1DL5CXOUCWNFG1A" FOREIGN KEY ("DSPCH_NO")
	  REFERENCES "TEST_USER"."DSPCH" ("DSPCH_NO") ENABLE;
  ALTER TABLE "TEST_USER"."ORDERS" ADD CONSTRAINT "FK2YXIH6I053RNPDWC6UH9XG3QJ" FOREIGN KEY ("FRM_ADDR_ID")
	  REFERENCES "TEST_USER"."ADDRESS" ("ADDR_ID") ENABLE;
  ALTER TABLE "TEST_USER"."ORDERS" ADD CONSTRAINT "FKAG8PPNKJVX255GJ7LM3M18WKJ" FOREIGN KEY ("PAYMENT_ID")
	  REFERENCES "TEST_USER"."PAYMENT" ("PAYMENT_ID") ENABLE;
  ALTER TABLE "TEST_USER"."ORDERS" ADD CONSTRAINT "FKOCU77VHVSCHDG0M5MFB0IIGA7" FOREIGN KEY ("TO_ADDR_ID")
	  REFERENCES "TEST_USER"."ADDRESS" ("ADDR_ID") ENABLE;
  ALTER TABLE "TEST_USER"."ORDERS" ADD CONSTRAINT "FKN82VYRY81Y8Y8JJXVT8W14TQP" FOREIGN KEY ("USER_ID")
	  REFERENCES "TEST_USER"."BAROGO_USER" ("USER_ID") ENABLE;
